### ISSUE TITLE
Add entrypoint to Docker image to allow injection of uid into `/etc/passwod`

### ISSUE THREAD

**Issue by dsclassen** [bl1231/bilbomd-worker#582]
`CHARMM` requires a username when it starts
If running `bilbomd-worker` in dev mode and bind mounting your local directories into the running container we have been using the Docker compose configuration directives to override the UID/.GID that are baked into the image from the GitHub Action CI/CD build pipeline:

```yaml
  worker:
    image: ghcr.io/bl1231/bilbomd-worker:1.14.0
    pull_policy: always
    env_file:
      - path: .env.dev
    networks:
      - app-network-dev
    volumes:
      # These are bind mounts that are used for local development
      - ./bilbomd-worker:/app # comment out to use beackend code in Docker image
      - ./uploads-dev:/bilbomd/uploads
      - ./logs/worker:/bilbomd/logs
    user: "${UID:-1001}:${GID:-1001}"
```

So the plan is to introduce a shell script so you can inject the dynamic `/etc/passwd` fix before running the actual command.

1. Create an entrypoint script

docker-entrypoint.sh:

```bash
#!/bin/sh
set -e

# Inject dynamic user into /etc/passwd if needed
if ! getent passwd "$(id -u)" > /dev/null; then
  echo "appuser:x:$(id -u):$(id -g):App User:/home/app:/bin/sh" >> /etc/passwd
fi

# Now run the real app (default to passed args, or npm start)
exec "$@"
```

2. Update your Dockerfile

```
# Copy your new entrypoint script
COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

# Use it as the entrypoint
ENTRYPOINT ["docker-entrypoint.sh"]

# Your original CMD stays as-is
CMD ["npm", "start"]
```

Hopefully ...
•	If your UID/GID is not found in /etc/passwd, it’ll inject one.
•	Then it runs npm start (or whatever command you pass via docker run ...).
